# Atividade SQLite

## Parte 1:

In [62]:
import sqlite3
import pandas as pd

In [63]:
conn = sqlite3.connect("empresa.db")
cursor = conn.cursor()

Código comentado para restaurar os dados:

In [64]:
#cursor.execute(""" DROP TABLE IF EXISTS Funcionarios """)#

### Criação de tabela (DDL):

In [65]:
cursor.execute("""
CREATE TABLE Funcionarios (
ID INTEGER PRIMARY KEY AUTOINCREMENT,
Nome TEXT NOT NULL,
Cargo TEXT NOT NULL,
Salario REAL,
Data_Contratacao TEXT NOT NULL
);
""")

Verificação da criação da tabela:

In [66]:
cursor.execute("SELECT name FROM sqlite_master;")
print(cursor.fetchall())

[('sqlite_sequence',), ('Funcionarios',)]

## Parte 2:

### Manipulação de Dados (DML):

In [67]:
cursor.executemany("INSERT INTO Funcionarios (Nome,Cargo, Salario, Data_Contratacao) VALUES (?,?,?,?)", [
('Lucas Almeida', 'Analista de Dados',4200,'2024-03-15'),
('Mariana Souza', 'Desenvolvedora Backend',5100,'2023-08-21'),
('Rafael Mendes', 'Técnico de Redes',3500,'2025-01-10'),
('Camila Ferreira', 'Analista de Suporte',3200,'2024-11-05'),
('Bruno Carvalho', 'Coordenador de TI',6800,'2022-06-18')
])

### Consulta Geral do Banco:

In [68]:
cursor.execute(""" SELECT * FROM Funcionarios """)
pd.DataFrame(cursor.fetchall())

   0                1                       2       3           4
0  1    Lucas Almeida       Analista de Dados  4200.0  2024-03-15
1  2    Mariana Souza  Desenvolvedora Backend  5100.0  2023-08-21
2  3    Rafael Mendes        Técnico de Redes  3500.0  2025-01-10
3  4  Camila Ferreira     Analista de Suporte  3200.0  2024-11-05
4  5   Bruno Carvalho       Coordenador de TI  6800.0  2022-06-18

### Consulta Filtrada do Banco:
Condições do Filtro:
- Selecione apenas os funcionários com salário superior a R$ 5.000.
- Selecione os funcionários que trabalham como 'Gerente'.

In [69]:
cursor.execute(""" SELECT * FROM Funcionarios WHERE Salario > 5000""")
pd.DataFrame(cursor.fetchall())

   0               1                       2       3           4
0  2   Mariana Souza  Desenvolvedora Backend  5100.0  2023-08-21
1  5  Bruno Carvalho       Coordenador de TI  6800.0  2022-06-18

In [70]:
cursor.execute(""" SELECT * FROM Funcionarios WHERE Cargo == 'Gerente' """)
pd.DataFrame(cursor.fetchall())

Empty DataFrame
Columns: []
Index: []

### Atualização de dados (UPDATE):

In [71]:
cursor.execute(""" UPDATE Funcionarios  SET Salario = Salario * 1.10 WHERE Nome == 'Lucas Almeida' """)
pd.DataFrame(cursor.fetchall())

Empty DataFrame
Columns: []
Index: []

Verificação do UPDATE:

In [72]:
cursor.execute(""" SELECT * FROM Funcionarios WHERE Nome == 'Lucas Almeida' """)
pd.DataFrame(cursor.fetchall())

   0              1                  2       3           4
0  1  Lucas Almeida  Analista de Dados  4620.0  2024-03-15

### Exclusão de dados (DELETE):

In [73]:
cursor.execute(""" DELETE FROM Funcionarios WHERE Nome = 'Bruno Carvalho'; """)

Verificação de DELETE:

In [74]:
cursor.execute(""" SELECT * FROM Funcionarios """)
pd.DataFrame(cursor.fetchall())

   0                1                       2       3           4
0  1    Lucas Almeida       Analista de Dados  4620.0  2024-03-15
1  2    Mariana Souza  Desenvolvedora Backend  5100.0  2023-08-21
2  3    Rafael Mendes        Técnico de Redes  3500.0  2025-01-10
3  4  Camila Ferreira     Analista de Suporte  3200.0  2024-11-05

### Contagem de registros no banco:

In [75]:
cursor.execute(""" SELECT COUNT(ID) FROM Funcionarios """)
cursor.fetchone()

(4,)

## Parte 3: Agregação e Ordenação

### Funções de agregação ( SUM, AVG, MAX, MIN):

Verificação da soma dos salários:

In [76]:
cursor.execute(""" SELECT SUM(Salario) FROM Funcionarios """)
cursor.fetchone()

(16420.0,)

Verificação da média dos salários:

In [77]:
cursor.execute(""" SELECT AVG(Salario) FROM Funcionarios """)
cursor.fetchone()

(4105.0,)

Verificação do maior salário:

In [78]:
cursor.execute(""" SELECT MAX(Salario) FROM Funcionarios """)
cursor.fetchone()

(5100.0,)

Verificação do menor salário:

In [79]:
cursor.execute(""" SELECT MIN(Salario) FROM Funcionarios """)
cursor.fetchone()

(3200.0,)

###  Agrupamento de dados ( GROUP BY):

Selecionando todos os funcionários e ordens de maior para o menor salário:

In [80]:
cursor.execute(""" SELECT Cargo, AVG (Salario) FROM Funcionarios GROUP BY Cargo""")
cursor.fetchall()

[('Analista de Dados', 4620.0),
 ('Analista de Suporte', 3200.0),
 ('Desenvolvedora Backend', 5100.0),
 ('Técnico de Redes', 3500.0)]

Selecione todos os funcionários e ordene-os por nome em ordem alfabética:

In [81]:
cursor.execute(""" SELECT Cargo, AVG (Salario) FROM Funcionarios GROUP BY Cargo""")
cursor.fetchall()

[('Analista de Dados', 4620.0),
 ('Analista de Suporte', 3200.0),
 ('Desenvolvedora Backend', 5100.0),
 ('Técnico de Redes', 3500.0)]

In [82]:
conn.commit()

## Parte 4: Transações e ROLLBACK:

### Simulação de transação:

Tentativa com simulação de erro:

In [83]:
try:
    conn.execute("BEGIN;")

    cursor.execute(""" INSERT INTO Funcionarios (Nome, Cargo, Salario, Data_Contratacao) VALUES ('Gerson Santana','Analista de Redes',7500 ,'2026-09-22') """)

    raise Exception("Erro simulado!")

    conn.commit()
except:
    conn.rollback()
    print("Transação revertida!")

Transação revertida!

Transação normal:

In [84]:
try:
    conn.execute("BEGIN;")

    cursor.execute(""" INSERT INTO Funcionarios (Nome, Cargo, Salario, Data_Contratacao) VALUES ('Gerson Santana','Analista de Redes',7500 ,'2026-09-22') """)

    conn.commit()
except:
    conn.rollback()
    print("Transação revertida!")

In [85]:
cursor.execute(" SELECT * FROM Funcionarios ")
pd.DataFrame(cursor.fetchall())

   0                1                       2       3           4
0  1    Lucas Almeida       Analista de Dados  4620.0  2024-03-15
1  2    Mariana Souza  Desenvolvedora Backend  5100.0  2023-08-21
2  3    Rafael Mendes        Técnico de Redes  3500.0  2025-01-10
3  4  Camila Ferreira     Analista de Suporte  3200.0  2024-11-05
4  6   Gerson Santana       Analista de Redes  7500.0  2026-09-22

## Parte 5: Joins e Múltiplas Tabelas:

### Criação de uma segunda tabela:

In [86]:
cursor.execute("""
CREATE TABLE Departamentos (
ID INTEGER PRIMARY KEY AUTOINCREMENT,
Nome_Departamento TEXT NOT NULL,
Localizacao TEXT
);
""")

In [88]:
cursor.executemany("INSERT INTO Departamentos (Nome_Departamento,Localizacao) VALUES (?,?)", [
('Dados', 'São Paulo'),
('Desenvolvimento', 'Campinas'),
('Infraestrutura e Suporte', 'São Paulo')
])

In [90]:
cursor.execute(" SELECT * FROM Departamentos ")
pd.DataFrame(cursor.fetchall())

   0                         1          2
0  1                     Dados  São Paulo
1  2           Desenvolvimento   Campinas
2  3  Infraestrutura e Suporte  São Paulo

In [91]:
conn.commit()

Adição de chave estrangeira (ALTER TABLE):

In [93]:
cursor.execute("ALTER TABLE Funcionarios ADD COLUMN ID_Departamento INT;")

In [98]:
cursor.executemany(""" UPDATE Funcionarios SET ID_Departamento = ? WHERE ID = ?
""",[(1, 1),(2, 2),(3, 3),(3, 4),(3, 6)]
)

In [99]:
cursor.execute(" SELECT * FROM Funcionarios ")
pd.DataFrame(cursor.fetchall())

   0                1                       2       3           4  5
0  1    Lucas Almeida       Analista de Dados  4620.0  2024-03-15  1
1  2    Mariana Souza  Desenvolvedora Backend  5100.0  2023-08-21  2
2  3    Rafael Mendes        Técnico de Redes  3500.0  2025-01-10  3
3  4  Camila Ferreira     Analista de Suporte  3200.0  2024-11-05  3
4  6   Gerson Santana       Analista de Redes  7500.0  2026-09-22  3